import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../providers/theme-provider";

import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import Navbar from "@/components/navbar";
import { Toaster } from "sonner";
import { FloatingNavDemo } from "@/components/floatingnav";
import CookieConsenInitilizer from "@/components/cookieconsent";
import ScrollProgressDemo from "@/components/ScrollProgressDemo";
import ScrollToTopButton from "@/components/ScrollToTop";
import MaxWidthWrapper from "@/components/max-width-wrapper";
import Footer from "@/components/footer";
import SmoothScroll from "@/components/SmoothScroll";
import { Pointer } from "@/components/cursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1.0,
  width: "device-width",
  maximumScale: 1.0,
  viewportFit: "cover",
  userScalable: false,
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <SpeedInsights />
      <Analytics />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MaxWidthWrapper>
          <FloatingNavDemo />
          <div>
            <ScrollProgressDemo /> <ScrollToTopButton />
          </div>
        </MaxWidthWrapper>
        {/* <SmoothScroll> */}
        <div className=" wrapper">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <MaxWidthWrapper>
              <Navbar />
            </MaxWidthWrapper>
            <div className="page-body">
              <CookieConsenInitilizer />
              {children}{" "}
            </div>
            <Footer /> <Toaster position="bottom-right" />
          </ThemeProvider>
        </div>
        {/* </SmoothScroll> */}
      </body>
    </html>
  );
}
